# Generated by Django 5.1.7 on 2025-03-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_class',
            name='phone_number_registr',
            field=models.IntegerField(),
        ),
    ]
