# Generated by Django 5.1.7 on 2025-03-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0002_alter_registration_class_phone_number_registr'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sign', models.CharField(max_length=100)),
                ('phone_number_sign', models.IntegerField()),
                ('gmail_person_sign', models.EmailField(max_length=254, unique=True)),
                ('password_sign', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registration_class',
            name='password_registr',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
