# Generated by Django 5.1.7 on 2025-03-21 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0003_login_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_class',
            name='created_at_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
