# Generated by Django 5.1.7 on 2025-03-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0004_registration_class_created_at_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_class',
            old_name='gmail_person_sign',
            new_name='gmail_person_login',
        ),
        migrations.RenameField(
            model_name='login_class',
            old_name='name_sign',
            new_name='name_sign_login',
        ),
        migrations.RenameField(
            model_name='login_class',
            old_name='password_sign',
            new_name='password_login',
        ),
        migrations.RenameField(
            model_name='login_class',
            old_name='phone_number_sign',
            new_name='phone_number_login',
        ),
    ]
