# Generated by Django 5.1.7 on 2025-03-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0005_rename_gmail_person_sign_login_class_gmail_person_login_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_class',
        ),
    ]
