# Generated by Django 5.1.7 on 2025-03-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0006_delete_login_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_class',
            name='password_registr',
            field=models.CharField(max_length=100),
        ),
    ]
