# Generated by Django 5.1.6 on 2025-03-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0008_menu_items_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items_class',
            name='price',
            field=models.IntegerField(),
        ),
    ]
