# Generated by Django 5.1.6 on 2025-03-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0009_alter_menu_items_class_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items_class',
            name='offer_price',
            field=models.IntegerField(),
        ),
    ]
