# Generated by Django 5.1.6 on 2025-03-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0010_alter_menu_items_class_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items_class',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/menu_photo/'),
        ),
    ]
