# Generated by Django 5.1.6 on 2025-03-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0011_alter_menu_items_class_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_items_class',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='menu_items_class',
            name='item_photo',
            field=models.ImageField(blank=True, null=True, upload_to='menu_photo/'),
        ),
    ]
