# Generated by Django 5.1.6 on 2025-03-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0012_remove_menu_items_class_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_item2_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name2', models.CharField(max_length=100, unique=True)),
                ('price2', models.IntegerField()),
                ('offer_price2', models.IntegerField()),
                ('time_set2', models.DateTimeField(auto_now=True)),
                ('item_photo2', models.ImageField(blank=True, null=True, upload_to='menu_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='menu_item3_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name3', models.CharField(max_length=100, unique=True)),
                ('price3', models.IntegerField()),
                ('offer_price3', models.IntegerField()),
                ('time_set3', models.DateTimeField(auto_now=True)),
                ('item_photo3', models.ImageField(blank=True, null=True, upload_to='menu_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='menu_item4_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name4', models.CharField(max_length=100, unique=True)),
                ('price4', models.IntegerField()),
                ('offer_price4', models.IntegerField()),
                ('time_set4', models.DateTimeField(auto_now=True)),
                ('item_photo4', models.ImageField(blank=True, null=True, upload_to='menu_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='menu_item5_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name5', models.CharField(max_length=100, unique=True)),
                ('price5', models.IntegerField()),
                ('offer_price5', models.IntegerField()),
                ('time_set5', models.DateTimeField(auto_now=True)),
                ('item_photo5', models.ImageField(blank=True, null=True, upload_to='menu_photo/')),
            ],
        ),
        migrations.RenameModel(
            old_name='menu_items_class',
            new_name='menu_item1_class',
        ),
        migrations.RenameField(
            model_name='menu_item1_class',
            old_name='item_name',
            new_name='item_name1',
        ),
        migrations.RenameField(
            model_name='menu_item1_class',
            old_name='item_photo',
            new_name='item_photo1',
        ),
        migrations.RenameField(
            model_name='menu_item1_class',
            old_name='offer_price',
            new_name='offer_price1',
        ),
        migrations.RenameField(
            model_name='menu_item1_class',
            old_name='price',
            new_name='price1',
        ),
        migrations.RenameField(
            model_name='menu_item1_class',
            old_name='time_set',
            new_name='time_set1',
        ),
    ]
