# Generated by Django 5.1.6 on 2025-03-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0013_menu_item2_class_menu_item3_class_menu_item4_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='menu_item_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('offer_price', models.IntegerField()),
                ('time_set', models.DateTimeField(auto_now=True)),
                ('item_photo', models.ImageField(blank=True, null=True, upload_to='menu_photo/')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='menu_item1_class',
        ),
        migrations.DeleteModel(
            name='menu_item2_class',
        ),
        migrations.DeleteModel(
            name='menu_item3_class',
        ),
        migrations.DeleteModel(
            name='menu_item4_class',
        ),
        migrations.DeleteModel(
            name='menu_item5_class',
        ),
    ]
