# Generated by Django 5.1.6 on 2025-03-26 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0014_category_menu_item_class_delete_menu_item1_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('offer_price', models.IntegerField(blank=True, null=True)),
                ('time_set', models.DateTimeField(auto_now=True)),
                ('item_photo', models.ImageField(blank=True, null=True, upload_to='menu_photo/')),
            ],
        ),
        migrations.DeleteModel(
            name='menu_item_class',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='app_.category'),
        ),
    ]
