# Generated by Django 5.1.6 on 2025-03-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0015_menuitem_delete_menu_item_class_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='offer_price',
            field=models.IntegerField(default=0),
        ),
    ]
